app/__init__.py
from flask import Flask
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Beverage, beverage_schema, beverages_schema

api = Blueprint('api',__name__, url_prefix='/api')


                                                                                #post contact test route

@api.route('/new_beverage', methods = ['POST'])
@token_required
def new_beverage(current_user_token):
    base_liquor = request.json['base_liquor']
    name = request.json['name']
    glass_type = request.json['glass_type']
    recipe = request.json['recipe']
    comments = request.json['comments']

    print(f'BIG TESTER: {current_user_token.token}')

    beverage = Beverage(base_liquor, name, glass_type, recipe,comments, user_token = current_user_token.token)

    db.session.add(beverage)
    db.session.commit()

    response = beverage_schema.dump(beverage)
    return jsonify(response)

                                                                                #retrieve all contacts route

@api.route('/beverages', methods = ['GET'])
@token_required
def list_all_beverages(current_user_token):
    a_user = current_user_token.token
    beverages = Beverage.query.filter_by(user_token = a_user).all()
    response = beverages_schema.dump(beverages)
    return jsonify(response)

                                                                                #retrieve single contact route by id

@api.route('/beverages/<id>', methods = ['GET'])
@token_required
def get_single_beverage(current_user_token,id):
    beverage = Beverage.query.get(id) 
    response = beverage_schema.dump(beverage)
    return response

                                                                                # update single contact by id

@api.route('/beverages/<id>', methods = ['POST','PUT'])
@token_required
def update_beverage_info(current_user_token,id):
    beverage = Beverage.query.get(id) 
    beverage.base_liquor = request.json['base_liquor']
    beverage.name = request.json['name']
    beverage.glass_type = request.json['glass_type']
    beverage.recipe = request.json['recipe']
    beverage.comments = request.json['comments']
    beverage.user_token = current_user_token.token

    db.session.commit()
    response = beverage_schema.dump(beverage)
    return jsonify(response)

                                                                                # delete single contact by id

@api.route('/beverages/<id>', methods = ['DELETE'])
@token_required
def delete_beverage(current_user_token, id):
    beverage = Beverage.query.get(id)
    db.session.delete(beverage)
    db.session.commit()
    response = beverage_schema.dump(beverage)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm, UserSignupForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

                                                                                # signup

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            first_name = form.first_name.data.title()
            last_name = form.last_name.data.title()
            favorite_liquor = form.favorite_liquor.data
            print(email, first_name, last_name, password)

            user = User(email, first_name, last_name, favorite_liquor, password = password)

            db.session.add(user)
            db.session.commit()



            flash(f'You have successfully created a user account {first_name} {last_name}', 'User-created')
            return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

                                                                                #signin

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('User identified', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('You do not have access to this content.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

                                                                                #Logout

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('landing.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/CSS/custom.min.css">
<link rel="stylesheet" href="../static/CSS/main.css">
<title>Beverage Collection</title>
</head>

<body class="bg-four_th">
    <nav class="navbar navbar-expand-lg bg-one_st navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Beverage Collection</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse color-secondary" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>                    
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>  
                    {% else %}  
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
        </div>
        
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="container-fluid bg-one_st fixed-bottom">
            <div class="row">
                <div class="d-flex p-3 align-items-center justify-content-center">
                    <h4 class="text-two_nd"> All photo credit to undraw.co </h4>
                </div>

            </div>
        </div>
    </footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/form.html
<form class="m-5" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Please enter valid email') }}
        </fieldset>
       <!-- <p>{{ request.path == "/signup" }}</p> -->
    </div>

    {% if request.path == "/signup" %}

    <div class="form-group">
        <fieldset id="name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = 'form-control', placeholder = 'Please enter first name') }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = 'form-control', placeholder = 'Please enter last name') }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="name-field">
            {{ form.favorite_liquor.label }}
            {{ form.favorite_liquor(class = 'form-control', placeholder = 'Please enter favorite liquor') }}
        </fieldset>
    </div>

    {% endif %}

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Please enter password") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-two_nd btn-outline-one_st btn-block mt-2")}}
</form>